### ISSUE TITLE
hand off maintenance

### ISSUE THREAD

**Issue by whit537** [whit537/mongs#26]
@jaraco You interested in taking over maintenance of Mongs? :-)

**Comment by jaraco** [comment]
I honestly don't have time to take on another project, but I'd happily accept the maintainer role to facilitate the resolution of the issues that affect us (and consequences of those changes).

**Comment by whit537** [comment]
@jaraco Fair enough. I've invited you as a collaborator here on GitHub. Looks like I've never packaged up and released Mongs on PyPI, so that's moot.

Welcome aboard, @jaraco! :-)
